### PR TITLE
Juce 6; Submodules; Deprecation; and OSes

### PR DESCRIPTION
**Pull request by baconpaul**
This diff does a couple of things

1. Remove the copied VST2SDK and Maximillian libraries and JuceLibraryCode generated assets
2. Add JUCE6 and Maximillian as git submodules
3. Create a CMakeFile which builds the assets with JUCE6 CMake
4. Removes the various derprecation warnings for JUCE6
5. Confirms the resulting synth works on mac linux and win
   as standalone VST3 and (mac) AU

I note the codebase doesn't have a license. To use JUCE in this
way I think you may need to be GPL3 or have a JUCE license.

If you want to build this version you use the sort of standard cmake procedurs

```
git clone
cd ATLASE-06-Synthesizer
git submodule update --init --recursive
cmake -Bbuild  # mac man want cmake -Bbuild -GXcode
cmake --build build --config Release
```

above works for me on macos 10.15.4, win10 and ubuntu 20.04 no problem.

And feel free to merge this or not or ask for changes or whatever you want. I was just helping a collaborator who wanted your synth on linux! Hope it helps!

### CODE REVIEW

**Comment by tank-trax** [comment]
I can confirm that this successfully built both the VST3 and Standalone instruments on Linux Debian Buster 10.3 using cmake 3.16

the VST3 loads in Reaper, Bitwig and Carla and the Standalone has ALSA and JACK support

**Comment by sbadon122** [comment]
Ahh neat, I'll check it out. Thanks!

**Comment by sbadon122** [comment]
These changes look good, I'm probably gonna merge them in. The only suggestion I have is the synthFramework.jucer doesn't support the new project structure and needs to updated. I can't assume everyone wants to use cmake.

**Comment by baconpaul** [comment]
oh yeah sure sorry we've moved to cmake only on our synths. lemme take a look and see if I can make the projucer work also and do another push for you in the next day or two OK?

**Comment by sbadon122** [comment]
Awesome thanks baconpaul! No rush. I appreciate the pull request.

**Comment by baconpaul** [comment]
Oh by the way, over in our other synths we have activated azure pipelines, which are free microsoft resources for OSS projects. Using them I'm able to build binaries of master automatically and put them up as GitHub releases. If that sounds like something you would want to do here let me know and I'll send over some information on an issue

**Comment by baconpaul** [comment]
OK just force pushed a version with the .jucer file correct

I notice the filter cutoff is behaving a little oddly though. Not particularly smooth. I wonder if that is a bug I introduced. Lemme take a look (unless you want to).

**Comment by sbadon122** [comment]
Oh wow that would be awesome. If you're feeling up to it, I'm open to the addition. I can look into that filter cutoff bug some time this week.

**Comment by baconpaul** [comment]
yeah you have to do an administrative thing but I will write it up this week. I wrote up a version for rack and did it with our synths too. lemme just make sure the filter cutoff isn't my fault in moving stuff around before you look. Thanks!

**Comment by baconpaul** [comment]
The filter thing was user error - the interaction between the filter envelope setting and the filter cutoff setting didn't work how I expected. (If you set the filter envelope high then the cutoff basically becomes a two value switch around 0.5). That's not related to my changes I don't think but is a separate issue.

So I think (think) this is good to merge if you want.

Oh the other thing I should say and I can't believe I didn't mention this - JUCE6 is in technical preview now. It seems pretty rock solid to me, but when Juce 6.0.0 ships in June or so we will need to update the submodule pointer to get the latest version. Don't know if that makes you hold off or not.

**Comment by sbadon122** [comment]
Cool good to hear. I'll review it tomorrow. Thanks!

**Comment by sbadon122** [comment]
Awesome looks good. Thanks for the help. Merging this in

**Pull request merged**
